[package]
name = "yucpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.0.1"
colored = "2.0.0"
regex = "1.7.1"
